name: Keep Supabase Projects Awake

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase Project 1
        run: |
          curl -I https://hptogvxjoyrpzlriiryv.supabase.co || true

      - name: Ping Supabase Project 2
        run: |
          curl -I https://xeguwajqiodghnensykt.supabase.co || true
